/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Controller.ControllerEmpleado;

/**
 *
 * @author Usuario
 */
public class EmpleadosMenu extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form EmpleadosMenu
     */
    public EmpleadosMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarra = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombredelEmpleado = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        Puesto = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        btnGuardarEmple = new javax.swing.JButton();
        btnActualizarEmple = new javax.swing.JButton();
        btnConsultarEmple = new javax.swing.JButton();
        btnEliminarEmple = new javax.swing.JButton();
        imageLogoEmple = new javax.swing.JLabel();
        btnRegresarEmple = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        txtYearInven1 = new javax.swing.JTextField();
        Year1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarra.setBackground(new java.awt.Color(0, 0, 0));
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
        });

        btnEmpleados.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(255, 0, 0));
        btnEmpleados.setText("X");
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setContentAreaFilled(false);
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Liv - Empleados");

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBarraLayout.setVerticalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLayout.createSequentialGroup()
                .addComponent(btnEmpleados)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 30));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        info.setForeground(new java.awt.Color(0, 0, 0));
        info.setText("Ingresa la información correspondiente");
        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 40));

        jSeparator1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 810, 10));

        txtNombredelEmpleado.setBackground(new java.awt.Color(236, 236, 236));
        txtNombredelEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombredelEmpleado.setCaretColor(new java.awt.Color(0, 0, 0));
        txtNombredelEmpleado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombredelEmpleado.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtNombredelEmpleado.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtNombredelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 30));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setText("Nombre del empelado");
        jPanel2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 30));

        Edad.setBackground(new java.awt.Color(255, 255, 255));
        Edad.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        Edad.setForeground(new java.awt.Color(0, 0, 0));
        Edad.setText("Edad");
        jPanel2.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, 30));

        txtEdad.setBackground(new java.awt.Color(236, 236, 236));
        txtEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEdad.setCaretColor(new java.awt.Color(0, 0, 0));
        txtEdad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEdad.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtEdad.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 240, 30));

        Phone.setBackground(new java.awt.Color(255, 255, 255));
        Phone.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        Phone.setForeground(new java.awt.Color(0, 0, 0));
        Phone.setText("Phone Number");
        jPanel2.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        txtPhone.setBackground(new java.awt.Color(236, 236, 236));
        txtPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPhone.setCaretColor(new java.awt.Color(0, 0, 0));
        txtPhone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPhone.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtPhone.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 30));

        Puesto.setBackground(new java.awt.Color(255, 255, 255));
        Puesto.setFont(new java.awt.Font("Baskerville Old Face", 0, 15)); // NOI18N
        Puesto.setForeground(new java.awt.Color(0, 0, 0));
        Puesto.setText("Puesto Encargado");
        jPanel2.add(Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 160, 30));

        txtPuesto.setBackground(new java.awt.Color(236, 236, 236));
        txtPuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPuesto.setCaretColor(new java.awt.Color(0, 0, 0));
        txtPuesto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPuesto.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtPuesto.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 240, 30));

        btnGuardarEmple.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardarEmple.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnGuardarEmple.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarEmple.setText("Guardar");
        btnGuardarEmple.setBorder(null);
        btnGuardarEmple.setBorderPainted(false);
        btnGuardarEmple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 100, 30));

        btnActualizarEmple.setBackground(new java.awt.Color(0, 153, 204));
        btnActualizarEmple.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnActualizarEmple.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarEmple.setText("Actualizar");
        btnActualizarEmple.setBorder(null);
        btnActualizarEmple.setBorderPainted(false);
        btnActualizarEmple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEmpleActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 100, 30));

        btnConsultarEmple.setBackground(new java.awt.Color(255, 153, 51));
        btnConsultarEmple.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnConsultarEmple.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarEmple.setText("Consultar");
        btnConsultarEmple.setBorder(null);
        btnConsultarEmple.setBorderPainted(false);
        btnConsultarEmple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEmpleActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 30));

        btnEliminarEmple.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminarEmple.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEliminarEmple.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEmple.setText("Eliminar");
        btnEliminarEmple.setBorder(null);
        btnEliminarEmple.setBorderPainted(false);
        btnEliminarEmple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 100, 30));

        imageLogoEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Resources/logoFinal.png"))); // NOI18N
        jPanel2.add(imageLogoEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 100, 100));

        btnRegresarEmple.setBackground(new java.awt.Color(255, 255, 0));
        btnRegresarEmple.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnRegresarEmple.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarEmple.setText("Regresar");
        btnRegresarEmple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegresarEmple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarEmpleActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresarEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 130, 20));

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaEmpleados);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 560, 280));

        txtYearInven1.setBackground(new java.awt.Color(236, 236, 236));
        txtYearInven1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtYearInven1.setCaretColor(new java.awt.Color(0, 0, 0));
        txtYearInven1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtYearInven1.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtYearInven1.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtYearInven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 300, 30));

        Year1.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        Year1.setForeground(new java.awt.Color(0, 0, 0));
        Year1.setText("Filtro");
        jPanel2.add(Year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 740, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        LoginLiv menu = new LoginLiv();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnRegresarEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarEmpleActionPerformed
        // TODO add your handling code here:
        MenuPrincipalLiv menu = new MenuPrincipalLiv();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarEmpleActionPerformed

    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraMousePressed

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
        // TODO add your handling code here:
        int x =  evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraMouseDragged

    private void btnGuardarEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombredelEmpleado.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String telefono = txtPhone.getText();
        String puesto = txtPuesto.getText();
        ControllerEmpleado.guardar(nombre, edad, telefono, puesto);
    }//GEN-LAST:event_btnGuardarEmpleActionPerformed

    private void btnActualizarEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEmpleActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombredelEmpleado.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String telefono = txtPhone.getText();
        String puesto = txtPuesto.getText();
        ControllerEmpleado.actualizar(nombre, edad, telefono, puesto);
    }//GEN-LAST:event_btnActualizarEmpleActionPerformed

    private void btnConsultarEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEmpleActionPerformed
        // TODO add your handling code here:
        ControllerEmpleado.consultar(TablaEmpleados);
    }//GEN-LAST:event_btnConsultarEmpleActionPerformed

    private void btnEliminarEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombredelEmpleado.getText();
        ControllerEmpleado.eliminar(nombre);
    }//GEN-LAST:event_btnEliminarEmpleActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Puesto;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JLabel Year1;
    private javax.swing.JButton btnActualizarEmple;
    private javax.swing.JButton btnConsultarEmple;
    private javax.swing.JButton btnEliminarEmple;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnGuardarEmple;
    private javax.swing.JButton btnRegresarEmple;
    private javax.swing.JLabel imageLogoEmple;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombredelEmpleado;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtYearInven1;
    // End of variables declaration//GEN-END:variables
}
