/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Controller.ControllerFactura;
import static Controller.ControllerFactura.tabla;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FacturasMenu extends javax.swing.JFrame {
    int xMouse, yMouse;
    public static DefaultTableModel model;

    /**
     * Creates new form FacturasMenu
     */
    public FacturasMenu() {
        initComponents();
        try{
            ControllerFactura.llenarTabla(tableFactura);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraFac = new javax.swing.JPanel();
        btnExitFacturas = new javax.swing.JButton();
        NameOfApp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Producto = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        NIT = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        Total = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFactura = new javax.swing.JTable();
        imageLogo = new javax.swing.JLabel();
        btnRegresarFactu = new javax.swing.JButton();
        txtFiltroInven = new javax.swing.JTextField();
        Filtro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarraFac.setBackground(new java.awt.Color(0, 0, 0));
        panelBarraFac.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraFacMouseDragged(evt);
            }
        });
        panelBarraFac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraFacMousePressed(evt);
            }
        });
        panelBarraFac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExitFacturas.setBackground(new java.awt.Color(0, 0, 0));
        btnExitFacturas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExitFacturas.setForeground(new java.awt.Color(255, 0, 51));
        btnExitFacturas.setText("X");
        btnExitFacturas.setBorder(null);
        btnExitFacturas.setBorderPainted(false);
        btnExitFacturas.setContentAreaFilled(false);
        btnExitFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitFacturasActionPerformed(evt);
            }
        });
        panelBarraFac.add(btnExitFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 30));

        NameOfApp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        NameOfApp.setForeground(new java.awt.Color(255, 255, 255));
        NameOfApp.setText("Liv - Facturas");
        panelBarraFac.add(NameOfApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 30));

        getContentPane().add(panelBarraFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        info.setForeground(new java.awt.Color(0, 0, 0));
        info.setText("Ingresa la información correspondiente");
        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 40));

        jSeparator1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 810, 10));

        Producto.setBackground(new java.awt.Color(255, 255, 255));
        Producto.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        Producto.setForeground(new java.awt.Color(0, 0, 0));
        Producto.setText("Producto ");
        jPanel2.add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 210, 30));

        txtProducto.setBackground(new java.awt.Color(236, 236, 236));
        txtProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProducto.setCaretColor(new java.awt.Color(0, 0, 0));
        txtProducto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProducto.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtProducto.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 240, 30));

        NIT.setBackground(new java.awt.Color(255, 255, 255));
        NIT.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        NIT.setForeground(new java.awt.Color(0, 0, 0));
        NIT.setText("NIT");
        jPanel2.add(NIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 30));

        txtNIT.setBackground(new java.awt.Color(236, 236, 236));
        txtNIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNIT.setCaretColor(new java.awt.Color(0, 0, 0));
        txtNIT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNIT.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtNIT.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 30));

        Total.setBackground(new java.awt.Color(255, 255, 255));
        Total.setFont(new java.awt.Font("Baskerville Old Face", 0, 15)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 0, 0));
        Total.setText("Total");
        jPanel2.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 40, 30));

        txtTotal.setBackground(new java.awt.Color(236, 236, 236));
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotal.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotal.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtTotal.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, 30));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 100, 30));

        btnActualizar.setBackground(new java.awt.Color(0, 153, 204));
        btnActualizar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 100, 30));

        btnConsultar.setBackground(new java.awt.Color(255, 153, 51));
        btnConsultar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setBorderPainted(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 100, 30));

        tableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableFactura);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 640, 280));

        imageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Resources/logoFinal.png"))); // NOI18N
        jPanel2.add(imageLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 100, 100));

        btnRegresarFactu.setBackground(new java.awt.Color(255, 255, 0));
        btnRegresarFactu.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnRegresarFactu.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarFactu.setText("Regresar");
        btnRegresarFactu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegresarFactu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarFactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarFactuActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresarFactu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 130, 20));

        txtFiltroInven.setBackground(new java.awt.Color(236, 236, 236));
        txtFiltroInven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFiltroInven.setCaretColor(new java.awt.Color(0, 0, 0));
        txtFiltroInven.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFiltroInven.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtFiltroInven.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtFiltroInven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroInvenKeyReleased(evt);
            }
        });
        jPanel2.add(txtFiltroInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 300, 30));

        Filtro.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        Filtro.setForeground(new java.awt.Color(0, 0, 0));
        Filtro.setText("Filtro");
        jPanel2.add(Filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitFacturasActionPerformed
        // TODO add your handling code here:
        LoginLiv menu = new LoginLiv();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitFacturasActionPerformed

    private void panelBarraFacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraFacMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraFacMousePressed

    private void panelBarraFacMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraFacMouseDragged
        // TODO add your handling code here:
        int x =  evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraFacMouseDragged

    private void btnRegresarFactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarFactuActionPerformed
    // TODO add your handling code here:
    MenuPrincipalLiv menu = new MenuPrincipalLiv();
    menu.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnRegresarFactuActionPerformed

    private void txtFiltroInvenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroInvenKeyReleased
        // TODO add your handling code here:
        String s = txtFiltroInven.getText();
        //ControllerFactura.tabla(s);
    }//GEN-LAST:event_txtFiltroInvenKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nit = txtNIT.getText();
        String producto = txtProducto.getText();
        int total = Integer.valueOf(txtTotal.getText());
        ControllerFactura.guardar(nit, producto, total);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        ControllerFactura.consultar(tableFactura);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String nit = txtNIT.getText();
        String producto = txtProducto.getText();
        int total = Integer.parseInt(txtTotal.getText());
        ControllerFactura.actualizar(nit, producto, total);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String nit = txtNIT.getText();
        ControllerFactura.eliminar(nit);
    }//GEN-LAST:event_btnEliminarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Filtro;
    private javax.swing.JLabel NIT;
    private javax.swing.JLabel NameOfApp;
    private javax.swing.JLabel Producto;
    private javax.swing.JLabel Total;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExitFacturas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresarFactu;
    private javax.swing.JLabel imageLogo;
    private javax.swing.JLabel info;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBarraFac;
    public static javax.swing.JTable tableFactura;
    public javax.swing.JTextField txtFiltroInven;
    public static javax.swing.JTextField txtNIT;
    public static javax.swing.JTextField txtProducto;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
