/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Usuario
 */
public class FacturasMenu extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form FacturasMenu
     */
    public FacturasMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraFac = new javax.swing.JPanel();
        btnExitFacturas = new javax.swing.JButton();
        NameOfApp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtID = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        productos = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        productos1 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        productos2 = new javax.swing.JLabel();
        txtID2 = new javax.swing.JTextField();
        productos3 = new javax.swing.JLabel();
        txtID3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarraFac.setBackground(new java.awt.Color(0, 0, 0));
        panelBarraFac.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraFacMouseDragged(evt);
            }
        });
        panelBarraFac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraFacMousePressed(evt);
            }
        });
        panelBarraFac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExitFacturas.setBackground(new java.awt.Color(0, 0, 0));
        btnExitFacturas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExitFacturas.setForeground(new java.awt.Color(255, 0, 51));
        btnExitFacturas.setText("X");
        btnExitFacturas.setBorder(null);
        btnExitFacturas.setBorderPainted(false);
        btnExitFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitFacturasActionPerformed(evt);
            }
        });
        panelBarraFac.add(btnExitFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 50, 30));

        NameOfApp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        NameOfApp.setForeground(new java.awt.Color(255, 255, 255));
        NameOfApp.setText("Liv");
        panelBarraFac.add(NameOfApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        getContentPane().add(panelBarraFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        info.setForeground(new java.awt.Color(0, 0, 0));
        info.setText("Ingresa la información correspondiente");
        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 40));

        jSeparator1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 520, 10));

        txtID.setBackground(new java.awt.Color(236, 236, 236));
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtID.setCaretColor(new java.awt.Color(0, 0, 0));
        txtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtID.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, 30));

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(0, 0, 0));
        ID.setText("Número de identificación de la factura");
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 230, 30));

        productos.setBackground(new java.awt.Color(255, 255, 255));
        productos.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        productos.setForeground(new java.awt.Color(0, 0, 0));
        productos.setText("Producto ");
        jPanel2.add(productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 210, 30));

        txtProducto.setBackground(new java.awt.Color(236, 236, 236));
        txtProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProducto.setCaretColor(new java.awt.Color(0, 0, 0));
        txtProducto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProducto.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtProducto.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 240, 30));

        productos1.setBackground(new java.awt.Color(255, 255, 255));
        productos1.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        productos1.setForeground(new java.awt.Color(0, 0, 0));
        productos1.setText("NIT");
        jPanel2.add(productos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 30));

        txtID1.setBackground(new java.awt.Color(236, 236, 236));
        txtID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtID1.setCaretColor(new java.awt.Color(0, 0, 0));
        txtID1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID1.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtID1.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 30));

        productos2.setBackground(new java.awt.Color(255, 255, 255));
        productos2.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        productos2.setForeground(new java.awt.Color(0, 0, 0));
        productos2.setText("Fecha de factura");
        jPanel2.add(productos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 30));

        txtID2.setBackground(new java.awt.Color(236, 236, 236));
        txtID2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtID2.setCaretColor(new java.awt.Color(0, 0, 0));
        txtID2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID2.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtID2.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 30));

        productos3.setBackground(new java.awt.Color(255, 255, 255));
        productos3.setFont(new java.awt.Font("Baskerville Old Face", 0, 15)); // NOI18N
        productos3.setForeground(new java.awt.Color(0, 0, 0));
        productos3.setText("Total");
        jPanel2.add(productos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, 30));

        txtID3.setBackground(new java.awt.Color(236, 236, 236));
        txtID3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtID3.setCaretColor(new java.awt.Color(0, 0, 0));
        txtID3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID3.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtID3.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Resources/LivLogo2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 110, 120));

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Guardar");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 100, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Actualizar");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 100, 30));

        jButton4.setBackground(new java.awt.Color(255, 153, 51));
        jButton4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Consultar");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 100, 30));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Eliminar");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 480, 280));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 550, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitFacturasActionPerformed
        // TODO add your handling code here:
        LoginLiv menu = new LoginLiv();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitFacturasActionPerformed

    private void panelBarraFacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraFacMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraFacMousePressed

    private void panelBarraFacMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraFacMouseDragged
        // TODO add your handling code here:
        int x =  evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraFacMouseDragged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel NameOfApp;
    private javax.swing.JButton btnExitFacturas;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelBarraFac;
    private javax.swing.JLabel productos;
    private javax.swing.JLabel productos1;
    private javax.swing.JLabel productos2;
    private javax.swing.JLabel productos3;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtID3;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
