/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Usuario
 */
public class FacturasMenu extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form FacturasMenu
     */
    public FacturasMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraFac = new javax.swing.JPanel();
        btnExitFacturas = new javax.swing.JButton();
        NameOfApp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        info = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtID = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        Producto = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        NIT = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        FechaDeFactura = new javax.swing.JLabel();
        txtFechaFactura = new javax.swing.JTextField();
        Total = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFactura = new javax.swing.JTable();
        imageLogo = new javax.swing.JLabel();
        btnGuardarInven1 = new javax.swing.JButton();
        btnRegresarFactu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarraFac.setBackground(new java.awt.Color(0, 0, 0));
        panelBarraFac.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraFacMouseDragged(evt);
            }
        });
        panelBarraFac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraFacMousePressed(evt);
            }
        });
        panelBarraFac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExitFacturas.setBackground(new java.awt.Color(0, 0, 0));
        btnExitFacturas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExitFacturas.setForeground(new java.awt.Color(255, 0, 51));
        btnExitFacturas.setText("X");
        btnExitFacturas.setBorder(null);
        btnExitFacturas.setBorderPainted(false);
        btnExitFacturas.setContentAreaFilled(false);
        btnExitFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitFacturasActionPerformed(evt);
            }
        });
        panelBarraFac.add(btnExitFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 50, 30));

        NameOfApp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        NameOfApp.setForeground(new java.awt.Color(255, 255, 255));
        NameOfApp.setText("Liv");
        panelBarraFac.add(NameOfApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 160, 30));

        getContentPane().add(panelBarraFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        info.setForeground(new java.awt.Color(0, 0, 0));
        info.setText("Ingresa la información correspondiente");
        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 40));

        jSeparator1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 810, 10));

        txtID.setBackground(new java.awt.Color(236, 236, 236));
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtID.setCaretColor(new java.awt.Color(0, 0, 0));
        txtID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtID.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtID.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 30));

        ID.setBackground(new java.awt.Color(255, 255, 255));
        ID.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(0, 0, 0));
        ID.setText("Número de identificación de la factura");
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 30));

        Producto.setBackground(new java.awt.Color(255, 255, 255));
        Producto.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        Producto.setForeground(new java.awt.Color(0, 0, 0));
        Producto.setText("Producto ");
        jPanel2.add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 210, 30));

        txtProducto.setBackground(new java.awt.Color(236, 236, 236));
        txtProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProducto.setCaretColor(new java.awt.Color(0, 0, 0));
        txtProducto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtProducto.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtProducto.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 240, 30));

        NIT.setBackground(new java.awt.Color(255, 255, 255));
        NIT.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        NIT.setForeground(new java.awt.Color(0, 0, 0));
        NIT.setText("NIT");
        jPanel2.add(NIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, 30));

        txtNIT.setBackground(new java.awt.Color(236, 236, 236));
        txtNIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNIT.setCaretColor(new java.awt.Color(0, 0, 0));
        txtNIT.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNIT.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtNIT.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 240, 30));

        FechaDeFactura.setBackground(new java.awt.Color(255, 255, 255));
        FechaDeFactura.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        FechaDeFactura.setForeground(new java.awt.Color(0, 0, 0));
        FechaDeFactura.setText("Fecha de factura");
        jPanel2.add(FechaDeFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        txtFechaFactura.setBackground(new java.awt.Color(236, 236, 236));
        txtFechaFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFechaFactura.setCaretColor(new java.awt.Color(0, 0, 0));
        txtFechaFactura.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFechaFactura.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtFechaFactura.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 30));

        Total.setBackground(new java.awt.Color(255, 255, 255));
        Total.setFont(new java.awt.Font("Baskerville Old Face", 0, 15)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 0, 0));
        Total.setText("Total");
        jPanel2.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, 30));

        txtTotal.setBackground(new java.awt.Color(236, 236, 236));
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotal.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotal.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtTotal.setSelectionColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 240, 30));

        btnGuardar.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 100, 30));

        btnActualizar.setBackground(new java.awt.Color(0, 153, 204));
        btnActualizar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.setBorderPainted(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 100, 30));

        btnConsultar.setBackground(new java.awt.Color(255, 153, 51));
        btnConsultar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(null);
        btnConsultar.setBorderPainted(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 100, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 100, 30));

        tableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableFactura);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 640, 280));

        imageLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Resources/logoFinal.png"))); // NOI18N
        jPanel2.add(imageLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 100, 100));

        btnGuardarInven1.setBackground(new java.awt.Color(255, 255, 0));
        btnGuardarInven1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnGuardarInven1.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarInven1.setText("Regresar");
        btnGuardarInven1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGuardarInven1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnGuardarInven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, 130, 20));

        btnRegresarFactu.setBackground(new java.awt.Color(255, 255, 0));
        btnRegresarFactu.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnRegresarFactu.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarFactu.setText("Regresar");
        btnRegresarFactu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegresarFactu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarFactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarFactuActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresarFactu, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 440, 130, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitFacturasActionPerformed
        // TODO add your handling code here:
        LoginLiv menu = new LoginLiv();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitFacturasActionPerformed

    private void panelBarraFacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraFacMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraFacMousePressed

    private void panelBarraFacMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraFacMouseDragged
        // TODO add your handling code here:
        int x =  evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraFacMouseDragged

    private void btnRegresarFactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarFactuActionPerformed
    // TODO add your handling code here:
    MenuPrincipalLiv menu = new MenuPrincipalLiv();
    menu.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnRegresarFactuActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaDeFactura;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel NIT;
    private javax.swing.JLabel NameOfApp;
    private javax.swing.JLabel Producto;
    private javax.swing.JLabel Total;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExitFacturas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarInven1;
    private javax.swing.JButton btnRegresarFactu;
    private javax.swing.JLabel imageLogo;
    private javax.swing.JLabel info;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBarraFac;
    private javax.swing.JTable tableFactura;
    private javax.swing.JTextField txtFechaFactura;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
