/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Controller.ControllerLogin;
import java.awt.Color;
import javax.swing.JOptionPane;



/**
 *
 * @author ruth
 */
public class LoginLiv extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    /**
     * Creates new form MenuPrincipal
     */
    public LoginLiv() {
        initComponents();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        nameOfApp = new javax.swing.JLabel();
        panleBarraLogin = new javax.swing.JPanel();
        l = new javax.swing.JButton();
        panelImage = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        contraLogin = new javax.swing.JLabel();
        nameOfLogin = new javax.swing.JLabel();
        nombreLogin = new javax.swing.JLabel();
        separadorNombre = new javax.swing.JSeparator();
        separadorContra = new javax.swing.JSeparator();
        btnOfRegistro = new javax.swing.JButton();
        btnOfSiguiente = new javax.swing.JButton();
        txtPaswordLogin = new javax.swing.JPasswordField();
        txtNombreLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(675, 466));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameOfApp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        nameOfApp.setForeground(new java.awt.Color(255, 255, 255));
        nameOfApp.setText("Liv");
        jPanel3.add(nameOfApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 30));

        panleBarraLogin.setBackground(new java.awt.Color(0, 0, 0));
        panleBarraLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panleBarraLoginMouseDragged(evt);
            }
        });
        panleBarraLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panleBarraLoginMousePressed(evt);
            }
        });
        panleBarraLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l.setBackground(new java.awt.Color(0, 0, 0));
        l.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l.setForeground(new java.awt.Color(255, 0, 51));
        l.setText("X");
        l.setBorder(null);
        l.setBorderPainted(false);
        l.setContentAreaFilled(false);
        l.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l.setFocusPainted(false);
        l.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMouseClicked(evt);
            }
        });
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });
        panleBarraLogin.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 50, 30));

        jPanel3.add(panleBarraLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        panelImage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Resources/imageLogin.jpg"))); // NOI18N
        panelImage.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 370, 440));

        jPanel3.add(panelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 220, 440));

        contraLogin.setBackground(new java.awt.Color(255, 255, 255));
        contraLogin.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        contraLogin.setForeground(new java.awt.Color(0, 0, 0));
        contraLogin.setText("Contraseña");
        jPanel3.add(contraLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 120, 40));

        nameOfLogin.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        nameOfLogin.setForeground(new java.awt.Color(0, 0, 0));
        nameOfLogin.setText("LOGIN");
        jPanel3.add(nameOfLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 40));

        nombreLogin.setBackground(new java.awt.Color(255, 255, 255));
        nombreLogin.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        nombreLogin.setForeground(new java.awt.Color(0, 0, 0));
        nombreLogin.setText("Nombre");
        jPanel3.add(nombreLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 40));
        jPanel3.add(separadorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 223, 350, 10));
        jPanel3.add(separadorContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 350, 50));

        btnOfRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnOfRegistro.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnOfRegistro.setForeground(new java.awt.Color(0, 0, 0));
        btnOfRegistro.setText("Registrarse");
        btnOfRegistro.setBorder(null);
        btnOfRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOfRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(btnOfRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 110, 30));

        btnOfSiguiente.setBackground(new java.awt.Color(30, 160, 236));
        btnOfSiguiente.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnOfSiguiente.setForeground(new java.awt.Color(0, 0, 0));
        btnOfSiguiente.setText("Siguiente");
        btnOfSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOfSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOfSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfSiguienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnOfSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 110, 30));

        txtPaswordLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtPaswordLogin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPaswordLogin.setForeground(new java.awt.Color(225, 225, 225));
        txtPaswordLogin.setText("**********");
        txtPaswordLogin.setBorder(null);
        txtPaswordLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPaswordLoginMousePressed(evt);
            }
        });
        jPanel3.add(txtPaswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 350, 30));

        txtNombreLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreLogin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNombreLogin.setForeground(new java.awt.Color(225, 225, 225));
        txtNombreLogin.setText("Ingrese su nombre de usuario");
        txtNombreLogin.setBorder(null);
        txtNombreLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreLoginMousePressed(evt);
            }
        });
        jPanel3.add(txtNombreLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 192, 350, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lMouseClicked

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lActionPerformed

    private void panleBarraLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panleBarraLoginMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panleBarraLoginMousePressed

    private void panleBarraLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panleBarraLoginMouseDragged
        // TODO add your handling code here:
        int x =  evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panleBarraLoginMouseDragged

    private void txtNombreLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreLoginMousePressed
        // TODO add your handling code here:
         if (txtNombreLogin.getText().equals("Ingrese su nombre de usuario")){
        txtNombreLogin.setText("");
        txtNombreLogin.setForeground(Color.black);
        }
        
        if(String.valueOf(txtPaswordLogin.getPassword()).isEmpty()){
        txtPaswordLogin.setText("**********");
        txtPaswordLogin.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtNombreLoginMousePressed

    private void txtPaswordLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPaswordLoginMousePressed
        // TODO add your handling code here:
        if(txtNombreLogin.getText().isEmpty()){
        txtNombreLogin.setText("Ingrese su nombre de usuario");
        txtNombreLogin.setForeground(new Color(204,204,204));
        }
        
        if(String.valueOf(txtPaswordLogin.getPassword()).equals("**********")){
        txtPaswordLogin.setText("");
        txtPaswordLogin.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPaswordLoginMousePressed

    private void btnOfRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfRegistroActionPerformed
        // TODO add your handling code here:
    RegistroLiv r = new RegistroLiv();
    r.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnOfRegistroActionPerformed

    private void btnOfSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfSiguienteActionPerformed
        // TODO add your handling code here:
        
        String user = txtNombreLogin.getText();
        char[] contra = txtPaswordLogin.getPassword();
        String sContra = new String(contra);
        ControllerLogin cn = new ControllerLogin();
        
        if(cn.datosSafe(user,sContra)){
            MenuPrincipalLiv menu = new MenuPrincipalLiv();
            menu.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
        }
        
        
    }//GEN-LAST:event_btnOfSiguienteActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOfRegistro;
    private javax.swing.JButton btnOfSiguiente;
    private javax.swing.JLabel contraLogin;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton l;
    private javax.swing.JLabel nameOfApp;
    private javax.swing.JLabel nameOfLogin;
    private javax.swing.JLabel nombreLogin;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panleBarraLogin;
    private javax.swing.JSeparator separadorContra;
    private javax.swing.JSeparator separadorNombre;
    private javax.swing.JTextField txtNombreLogin;
    private javax.swing.JPasswordField txtPaswordLogin;
    // End of variables declaration//GEN-END:variables
}
